name: Master Build
on:
  push:
    branches:
      - master
jobs:
  master-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/pr-build.yaml
  master-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/pages-build.yaml
