name: Pages Build
on:
  workflow_call: {}

concurrency: preview-${{ github.ref }}

jobs:
  pages-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install mdBook
        run: |
          export DOWNLOAD_URL="https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz"
          curl --fail -O -L "${DOWNLOAD_URL}"
          tar xzf $(basename "${DOWNLOAD_URL}")
          sudo mv mdbook /usr/local/bin
          mdbook --version
      - name: Generate Pages
        run: |
          mdbook build docs
      - name: Check index.html
        run: |
          cat docs/book/index.html
