name: Pages Build
on:
  workflow_call: {}

concurrency: preview-${{ github.ref }}

jobs:
  pages-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install mdBook
        run: |
          export DOWNLOAD_URL="https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz"
          curl --fail -O -L "${DOWNLOAD_URL}"
          tar xzf $(basename "${DOWNLOAD_URL}")
          sudo mv mdbook /usr/local/bin
          mdbook --version
      - name: Generate Pages
        run: |
          mkdir -p build
          cat > build/index.html <<EOF
          <!DOCTYPE html>
          <html>
          <body>

          <h1>My First Heading</h1>
          <p>My first paragraph.</p>

          </body>
          </html>
          EOF
      - name: Check index.html
        run: |
          cat build/index.html
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
          preview-branch: gh-pages
