name: PR Close

on:
  pull_request:
    types:
      - closed
  workflow_call: {}

jobs:
  pr-close-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Remove prior docs preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./docs/book
          preview-branch: gh-pages
